config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :favorites, only: [:index]
  end
  resources :pictures do
    collection do
      post :confirm
    end
    resource :favorites, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates_uniqueness_of :picture_id, scope: :user_id
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, length: { maximum: 600 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  mount_uploader :icon, IconUploader
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # validates :password_confirmation, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      flash[:notice] = "ログインしてください"
      redirect_to new_session_path
    end
  end

  def update_user
    unless current_user.id == @user.id
      flash[:notice] = "操作権限がありません"
    redirect_to root_path
    end
  end

  def update_picture
    unless current_user.id == @picture.user.id
      flash[:notice] = "操作権限がありません"
    redirect_to root_path
    end
  end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user, {only: [:create, :destroy]}

  def index
    favorites = Favorite.includes(:picture).where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
    @pictures = favorites.map(&:picture)

    # # GOAL
    # [<favorite picture=<picture>>, <favorite picture=<picture>>, <favorite picture=<picture>>]
    # [<picture>, <picture>, <picture>]

    # # 1
    # @pictures = []
    # favorites.each do |f|
    #   @pictures << f.picture
    # end

    # # 2
    # @pictures = []
    # favorites.each { |f| @pictures << f.picture }

    # # 3
    # @pictures = favorites.map { |f| f.picture }

    # # 4
    # @pictures = favorites.map(&:picture)
  end

  def create
    favorite = current_user.favorites.build(picture_id: params[:picture_id])
    favorite.save
    redirect_to picture_path(Picture.find(params[:picture_id]))
  end

  def destroy
    favorite = Favorite.find_by(picture_id: params[:picture_id], user_id: current_user.id)
    favorite.destroy
    redirect_to picture_path(Picture.find(params[:picture_id]))
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :update_picture, only: [:edit, :update]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        redirect_to user_path(current_user.id), notice: "投稿が完了しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id), notice: "投稿内容を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to user_path(current_user.id), notice:"投稿を削除しました"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :update_user, {only: [:edit, :update]}

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "ユーザーを新規登録しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render  :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました"
    else
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<h1><%= @user.name %>のお気に入り一覧</h1>

<% if @pictures.present? %>
  <% @pictures.each do |picture| %>
    <p><%= image_tag picture.image.url %></p>
    <p><%= picture.content %></p>
  <% end %>
<% end %>

<%= link_to '戻る', user_path(@user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kajistagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar text-white bg-dark">
      <div class="container">
        <div class="nabar-header">
          <%= link_to root_path, class:"logo" do %>
            <h1>Kajistagram</h1>
          <% end %>
            <% flash.each do |key, value| %>
              <%= content_tag(:div, value, class: "#{key}") %>
            <% end %>
            <% if logged_in? %>
              <%= link_to "Profile", user_path(current_user.id) %>
              <%= link_to "Log out", session_path(current_user.id), method: :delete %>
              <%= link_to "New post", new_picture_path %>
            <% else %>
              <%= link_to "Sign up", new_user_path %>
              <%= link_to "Log in", new_session_path %>
            <% end %>
        </div>
      </div>
    </header>
    <div class="container mb-5">
    <%= yield %>
    </div>
    <footer class="footer fixed-bottom">
      <div class="container">
        <p class="text-center">Copyright © 2021 WEF2101 Kajiyama Yuuki.</span>
      </div>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |messeage| %>
        <li><%= messeage %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <%= form.text_field :content %>
    <%= form.submit "投稿する"%>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>以下の内容で送信する</h1>
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <%= form.hidden_field :content %>
  <p><%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "送信する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>投稿編集</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<% @pictures.each do |picture| %>
<p><%= image_tag picture.image.url %></p>
<p><%= link_to "詳細", picture_path(picture.id) %></p>
<% end %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<p><%= notice %></p>

<p>投稿者：<%= @picture.user.name %></p>

<p>
<%= image_tag @picture.image.url %>
</p>

<p><%= @picture.content %></p>

<% if @picture.user_id == current_user.id %>
  <p><span>お気に入り数：</span><%= @picture.favorites.count %></p>
  <%= link_to "編集", edit_picture_path(@picture.id), data: { confirm: '本当に編集してよろしいですか？' } %>
  <%= link_to "削除", picture_path(@picture.id), method: :delete ,data: { confirm: '本当に削除してよろしいですか？' } %>
<% else %>
  <% if @picture.favorited_by?(current_user) %>
    <p><span>お気に入り解除：</span><%= link_to @picture.favorites.count, picture_favorites_path(@picture.id), method: :delete %></p>
  <% else %>
    <p><span>お気に入り登録：</span><%= link_to @picture.favorites.count, picture_favorites_path(@picture.id), method: :post %></p>
  <% end %>
<% end %>

<%= link_to '戻る', pictures_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= image_tag(@user.icon.url) if @user.icon && @user.icon.url %>
  <%= f.label :icon %>
  <%= f.file_field :icon %>
  <%= f.hidden_field :icon_cache %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p><%= notice %></p>
<p>プロフィール画像:
<% if @user.icon? %>
  <%= image_tag @user.icon.url %>
<% end %>
</p>
<p>ユーザーネーム:<%= @user.name %></p>
<p>メールアドレス:<%= @user.email %></p>
<%= link_to "お気に入り一覧", user_favorites_path(@user) %>

<% if logged_in? && @user.id == current_user.id %>
<p><%= link_to "プロフィール編集", edit_user_path(@user.id) %></p>
<% end %>

<% @user.pictures.each do |photo| %>
  <p><%= image_tag photo.image.url %></p>
  <p><%= link_to "show", picture_path(photo.id) %></p>
<% end %>